//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdfFlattener
{
    using System;
    using System.Collections.Generic;
    
    public partial class epoa_Requests
    {
        public int id { get; set; }
        public string RequestorName { get; set; }
        public string RequestorUserName { get; set; }
        public string RequestorEmail { get; set; }
        public string RequestorRegion { get; set; }
        public string RequestorPhone { get; set; }
        public string AgentCode { get; set; }
        public string LOB { get; set; }
        public string AgentCode_1 { get; set; }
        public string LOBR1 { get; set; }
        public string AgentCode_2 { get; set; }
        public string LOBR2 { get; set; }
        public string AgentCode_3 { get; set; }
        public string AgentName { get; set; }
        public string AgentAddress { get; set; }
        public string AgentAddress1 { get; set; }
        public string AgentCity { get; set; }
        public string AgentState { get; set; }
        public string AgentZip { get; set; }
        public string Region { get; set; }
        public string RegionCode { get; set; }
        public string RegionPhone { get; set; }
        public string AgencyEmail { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string DeliverToAttentionOf { get; set; }
        public string RO_Instructions { get; set; }
        public Nullable<System.DateTime> RO_RequestDate { get; set; }
        public string Status { get; set; }
        public string POA_Names { get; set; }
        public string POA_CityState { get; set; }
        public string LicensingHandler { get; set; }
        public string LicensingHandlerFullName { get; set; }
        public Nullable<System.DateTime> POAEmailDate { get; set; }
        public string POAEmail1 { get; set; }
        public string POAEmail2 { get; set; }
        public string POAEmail3 { get; set; }
        public string POAEmail4 { get; set; }
        public string HO_Instructions { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeUser { get; set; }
        public string POAPath { get; set; }
    }
}
